### ISSUE TITLE
Can it follow RESTful API like design?

### ISSUE THREAD

**Issue by shivaken** [anubnair/webapp#1]
Hi I'm Kenichi from ZALORA.
Would it be possible to follow RESTful like API design?

1. uploading file is ok. 
2. To retrieve file, sending POST request is a bit weird. Can it done by GET request?
3. To delete file, using DELETE http method is also a common pattern.

Could you consider about it? There are so many articles about RESTful API design. They might be helpful.

**Comment by anubnair** [comment]
Extremely sorry, I implemented upload and reused that portion of code! my carelessness. I have fixed the issue

1) upload - http://localhost:5000/upload (POST request)
2) retrieve file - http://localhost:5000/retrieve_file?filename=1.txt (GET request)
3) delete file - http://localhost:5000/delete?filename=1.txt (DELETE request)
Use curl -X "DELETE" http://localhost:5000/delete?filename=1.txt for validating delete file, I have not implemented any UI for it
